services:
  model-svc:
    build:
      context: .
      dockerfile: docker/model.Dockerfile
    ports: ["8002:8002"]
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8002/health')",
        ]
      interval: 10s
      timeout: 3s
      retries: 10

  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    ports: ["8080:8000"]
    depends_on:
      model-svc: { condition: service_healthy }
    environment:
      - MODEL_SVC_URL=http://model-svc:8002
      - THRESHOLDS_JSON=configs/dev/thresholds.json
      - JUDGE_BACKEND=stub
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')",
        ]
      interval: 10s
      timeout: 3s
      retries: 10
