# ============================================================
# PhishGuard Configuration - Development Environment
# ============================================================

# Model Service Configuration
model_service:
  # Primary model (production)
  primary:
    path: "models/dev/model_8feat.pkl"
    meta_path: "models/dev/model_8feat_meta.json"
    name: "8-feature-production-v1"
    description: "8-feature URL model with IsHTTPS (PR-AUC: 99.92%)"
  
  # Shadow model (DISABLED for production)
  shadow:
    enabled: false
    path: "models/dev/model_7feat.pkl"
    meta_path: "models/dev/model_7feat_meta.json"
    name: "7-feature-baseline"
    description: "7-feature URL model without IsHTTPS (research only)"
    log_path: "outputs/shadow_predictions.jsonl"

# Gateway Configuration
gateway:
  # Thresholds file (tuned on 8-feature model)
  thresholds_path: "configs/dev/thresholds.json"
  
  # Default thresholds (fallback if file load fails)
  default_thresholds:
    low: 0.004      # Auto-ALLOW below this (99.6% safe URLs)
    high: 0.999     # Auto-BLOCK at/above this (99.5% phishing)
    t_star: 0.350   # F1-optimal threshold
    gray_zone_rate: 0.109  # ~11% escalated to judge

# Feature Extraction Configuration
features:
  # TLD legitimacy lookup table (695 TLDs)
  tld_probs_path: "data/tld_probs.json"
  
  # Bayesian priors for TLD scoring
  tld_alpha: 1
  tld_beta: 2
  
  # Minimum samples for TLD reliability
  min_samples: 10
  
  # Fail-secure: return suspicious features on extraction errors
  fail_secure: true

# Logging Configuration
logging:
  level: "INFO"
  shadow_logging: false
  audit_enabled: false