# PhishGuard Configuration - Development Environment
# This file specifies which models to load and how to configure services

model_service:
  # Primary model - used for actual predictions/decisions
  primary:
    path: "models/dev/model_7feat.pkl"
    meta_path: "models/dev/model_7feat_meta.json"
    name: "7-feature-production"
    description: "URL-only model without IsHTTPS, robust to 2025 HTTPS phishing"
  
  # Shadow model - runs in parallel for A/B testing (optional)
  shadow:
    enabled: true  # Set to false to disable shadow testing
    path: "models/dev/model_8feat.pkl"
    meta_path: "models/dev/model_8feat_meta.json"
    name: "8-feature-research"
    description: "URL-only model with IsHTTPS for comparison"

gateway:
  # Thresholds must match the primary model
  thresholds_path: "configs/dev/thresholds_7feat.json"
  
  # Policy band configuration
  # These values can be overridden by the thresholds file
  default_thresholds:
    low: 0.20   # Auto-ALLOW below this
    high: 1.00  # Auto-BLOCK at/above this
    t_star: 0.60  # F1-optimal threshold

# Feature extraction configuration
features:
  # TLD probability lookup table
  tld_probs_path: "data/tld_probs.json"
  
  # Fail-secure behavior when feature extraction fails
  fail_secure: true  # If true, return suspicious features on error

# Logging configuration
logging:
  level: "INFO"
  shadow_logging: true  # Log shadow model predictions for analysis