# .github/workflows/ci.yml — CI/CD for 8-feature PhishGuard project
name: Tests
on:
  pull_request:
    branches: ["main"] # only runs on PRs into main
  workflow_dispatch: # allow manual runs from Actions tab

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Skip pywin32 on Linux runners, install everything else
          grep -v "pywin32" requirements.txt > requirements-linux.txt || cp requirements.txt requirements-linux.txt
          pip install -r requirements-linux.txt
          pip install pytest pytest-cov black isort flake8 mypy
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src:$(pwd)" >> $GITHUB_ENV
      - name: Code quality checks
        run: |
          black --check .
          isort --check-only .
          flake8 .
          mypy src
      - name: Run tests
        run: python -m pytest tests/ -v --tb=short
