# .github/workflows/ci.yml  (branch: feature/ci-gateway)
name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -U pip && pip install -e ".[dev]"
      - run: pytest -q
  build-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -f docker/gateway.Dockerfile -t phishguard-gateway:ci .
