# .github/workflows/ci.yml  — Option A (paused CI for feature/dev)
name: Tests
on:
  pull_request:
    branches: ["main"]   # only runs on PRs into main
  workflow_dispatch:      # allow manual runs from Actions tab

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black isort flake8 mypy
      - run: |
          black --check .
          isort --check-only .
          flake8 .
          mypy src
      - run: python -m pytest -q
